home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
	# ex: /home/
	url(r'^$', views.home, name='home'),
	# ex: /home/customdata/
	url(r'^customdata/$', views.customdata, name='customuserdata'),
]

inthenout/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^source/', include('source.urls')),
	url(r'^collection/', include('collection.urls')),
    url(r'^emailupdate/', include('emailupdate.urls')),
    url(r'^accounts/', include('allauth.urls')),
	url(r'^home/',include('home.urls')),
    url(r'^', include('welcome.urls')),
]

source/urls.py
from django.conf.urls import url

from . import views

app_name = 'source'
urlpatterns = [
	# ex: /source/
	url(r'^$', views.index, name='index'),
	# ex: /source/1/
	url(r'^(?P<source_id>[0-9]+)/$', views.detail, name='detail'),
	# ex: /source/category/..
	url(r'^category/(?P<category>[\w\-]+)/$', views.category, name='category'),
	# ex: /source/organization/..
	url(r'^organization/(?P<organization>[\w\-]+)/$', views.organization, name='organization'),
]

source/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.forms import ModelForm

class Source_Category(models.Model):
	name 			= models.CharField(max_length=50)
	date_created 	= models.DateTimeField(auto_now_add=True)
	description		= models.CharField(max_length=400)
	is_active		= models.BooleanField(default=True)
	
	def __str__(self):
		return self.name + " | " + self.description

class Source(models.Model):
	name 			= models.CharField(max_length=30)
	date_created 	= models.DateTimeField(auto_now_add=True)
	base_url 		= models.CharField(max_length=200)
	oauth_version	= models.IntegerField(default=0)
	rss_flag		= models.BooleanField(default=False)
	dict0_flag		= models.BooleanField(default=False)
	is_active		= models.BooleanField(default=True)
	description		= models.CharField(max_length=400)
	category		= models.ForeignKey(Source_Category, models.SET_NULL, blank=True, null=True,)
	organization	= models.CharField(max_length=100)
	
	def __str__(self):
		return self.name 

class Source_Variable(models.Model):
	source 			= models.ForeignKey(Source, on_delete=models.CASCADE)
	variable_name 	= models.CharField(max_length=100)
	variable_value 	= models.CharField(max_length=200)
	date_created 	= models.DateTimeField(auto_now_add=True)
	is_active 		= models.BooleanField(default=True)
	is_parameter 	= models.BooleanField(default=False)
	is_dummy 		= models.BooleanField(default=False)
	
	def __str__(self):
		return "{variable_name:" + self.variable_name + ",variable_value:" + self.variable_value + "}"
		#return str(self.source) + " " + self.variable_name + " " + self.variable_value}
		
class Source_User(models.Model):
	user 			= models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
	source 			= models.ForeignKey(Source, related_name='source', on_delete=models.CASCADE)
	date_created	= models.DateTimeField(auto_now_add=True)
	is_active		= models.BooleanField(default=True)
	
	def __str__(self):
		return str(self.source) + "_" + str(self.user)
		

class SourceUserForm(ModelForm):
    class Meta:
		model = Source_User
		exclude = ('user','source','date_created','is_active')
		

source/backup/views.py
from django.shortcuts import render,  get_object_or_404
import requests, datetime, feedparser

from .models import Source

context = {}

def index(request):
	sources = Source.objects.all()
	context = {'object_list':sources}
	return render(request, 'source/index.html', context)

#The function below parses RSS feeds and API calls	
def detail(request, source_id):
	context = {}
	source_object = Source.objects.get(pk=source_id)
	rss_flag = source_object.rss_flag
	dict0_flag = source_object.dict0_flag
	url = source_object.url
	oauth_version = source_object.oauth_version
	sourcename = {'name':source_object.name}
	urljson = {}
	if rss_flag:    
		url_parsed = feedparser.parse(url)		
		url_parsed0 = url_parsed.entries[0]
		url_feed = url_parsed.feed
		context['entries'] = url_parsed0
		context['feed'] = url_feed
	elif not rss_flag: 
	    if dict0_flag:
		    context['api'] = requests.get(url).json()[0]
	    else:
		    context['api'] = requests.get(url).json()
		
	context['source'] = sourcename
	return render(request, 'source/details.html', {'JSON': context})
	

source/views.py
from django.shortcuts import render,  get_object_or_404, redirect
import requests, datetime, feedparser
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Source, Source_Variable, Source_User, SourceUserForm, Source_Category
from collection.models import User_Collection
from django.contrib.auth.models import User

from inthenout.utils import apicall, navigationlinks

context = {}

def index(request):
	#Get all source objects
	sources = Source.objects.all()
	context = navigationlinks(request)
	#Assign context
	context['source_list'] = sources
	context['source_category'] = Source_Category.objects.all()
	context['source_organization'] = Source.objects.values('organization').distinct()
	return render(request, 'source/index.html', context)
	
def category(request, category):
	#Get all source objects
	sources = Source.objects.filter(category=category)
	context = navigationlinks(request)
	context['category'] = Source_Category.objects.filter(id=category)	
	context['source_list'] = sources
	return render(request, 'source/category.html',context)

def organization(request, organization):
	#Get all source objects
	sources = Source.objects.filter(organization=organization)
	context = navigationlinks(request)
	context['organization'] = organization 
	context['source_list'] = sources
	return render(request, 'source/organization.html',context)	
	
#The function below parses RSS feeds and API calls	
@login_required
def detail(request, source_id):
	#Assign variables
	user_object = request.user
	source_user_object = Source_User.objects.filter(user=user_object.id).filter(is_active=True)
	collection_object = User_Collection.objects.filter(user=user_object.id).filter(is_active=True)
	su_is_active = ""
	source_variable = []
	url_param = {}
	url_dict = {}
	user_object = request.user
	source_object = Source.objects.get(pk=source_id)
	source_var_check = Source_Variable.objects.filter(source_id=source_object.id).exists()
	source_user_check = Source_User.objects.filter(source=source_object.id).filter(user=user_object.id).exists()
	if source_user_check:
		#su_object = Source_User.objects.filter(source=source_object.id).filter(user=user_object.id)
		su_object = Source_User.objects.get(source=source_object.id, user=user_object.id)
		su_is_active = su_object.is_active
	if source_var_check:
		source_variable = Source_Variable.objects.filter(source_id=source_object.id).values('variable_name','variable_value')
	else:
		source_variable = []
	if request.method == "POST":
		form = SourceUserForm(request.POST)
		if not source_user_check:
			post = form.save(commit=False)
			post.user = user_object
			post.source = source_object
			post.date_created = timezone.now()
			post.is_active = True
			post.save()
			return redirect('/home/')
		else:
			su_object.is_active = not su_object.is_active
			su_object.save()
			return redirect('/home/')
	rss_flag = source_object.rss_flag
	dict0_flag = source_object.dict0_flag
	url = source_object.base_url
	oauth_version = source_object.oauth_version
	for dict in source_variable:
		url_param[str(dict['variable_name'])] = str(dict['variable_value'])
	sourcename = {'name':source_object.name}
	#Call function apicall to perform an api or rss call and parses the data into a flat format
	context = apicall(rss_flag, url, dict0_flag, sourcename, oauth_version, url_param)
	return render(request, 'source/details.html', {'JSON': context, 'su_check':source_user_check, 'su_is_active':su_is_active, 'object_list':source_user_object, 'collection_list':collection_object})

source/templates/source/category.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}
<div class="w3-container">
{% for category in category %}
	<div class="w3-left">
	<h5><i class="w3-left w3-margin-bottom" style="color: red">{{category.description }}</i></h5>
	<h1 class="w3-homecategory">{{ category.name }}</h1>
	</div>
{% endfor %}
</div>
<div class="w3-barnav w3-container">
	<div class="w3-left w3-margin-left">
		{% for source in source_list|dictsort:"name" %}
			{% if source.is_active is True%}
				<li class="w3-sourcelinks"><a class="w3-sourcelinks w3-margin-left w3-hover-red" href="{% url 'source:detail' source.id %}">{{ source.name }} - {{ source.description }}</a></li>
			{% endif %}
		{% endfor %}
		<br>
	</div>
</div>
{% endblock content %}

source/templates/source/details.html
{% extends "base.html" %}

{% block title %}Source - Available Data{% endblock title %}

{% block content %}
<div>
	<div>
	{% if su_check %}
		{% if su_is_active == True %}
			<form name="sourceremove" class="w3-text-red w3-padding w3-padding-bottom" method="Post">
			<button type="submit">Remove Source</button>
			{% csrf_token %}
			{{ form.as_p }}
			</form>
		{% else %}
			<form name="sourceremove" class="w3-text-red w3-padding w3-padding-bottom" method="Post">
			<button type="submit">Add Source</button>
			{% csrf_token %}
			{{ form.as_p }}
			</form>
			<br>
		{% endif %}
	{% else %}
	<form name="sourceadd" class="w3-padding w3-padding-bottom w3-text-red" method="Post">
	<button type="submit">Add to my Sources</button>
	{% csrf_token %}
	{{ form.as_p }}
	</form>
	{% endif %}
	</div>
	<div>
		<div class="w3-center">	
		<h1>{{ JSON.source_name }} Example</h1>
		</div>
		<div class="w3-sourcecontent">
			<div class="w3-center w3-border-top w3-border-bottom w3-padding-top">
			{% for key, value in JSON.items|dictsort:0 %}
				<div class="w3-row">
					<div class=" w3-left w3-third">
					<p class="" style="text-align:right;">{{ key }}</p>
					</div>
					<div class="w3-right w3-twothird w3-padding-left w3-padding-right" style="text-align:left; color:red;">
					<p>{{ value }}</p>
					</div>
				</div>
				{% for key2, value2 in value.items|dictsort:0 %}
					<div class="w3-row">
						<div class="w3-third w3-left" style="text-align:right;">
						<p>{{ key }}.{{ key2 }}</p>
						</div>
						<div class="w3-twothird w3-right w3-padding-left w3-padding-right" style="text-align:left; color:red;">
						<p>{{ value2 }}</p>
						</div>
					</div>
					{% for key3, value3 in value2.items %}
						<div class="w3-row">
							<div class="w3-third w3-left" style="text-align:right;">
							<p>{{ key2 }}.{{ key3 }}</p>
							</div>
							<div class="w3-twothird w3-right w3-padding-left w3-padding-right" style="text-align:left; color:red;">
							<p>{{ value3 }}</p>
							</div>
						</div>
					{% endfor %}
				{% endfor %}
			{% endfor %}
			</div>
		</div>
	</div><br>
</div>
{% endblock content %}

source/templates/source/details_old.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}
<p>TEST {{ source.id }} {{ source.name }}</p>

{% endblock content %}

source/templates/source/index.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}

<div class="w3-barnav w3-container">
	<div class="w3-third w3-left">
		<h2>Source</h2>
		{% for source in source_list|dictsort:"name" %}
			{% if source.is_active is True%}
				<li class="w3-sourcelinks"><a class="w3-sourcelinks w3-hover-red" href="{% url 'source:detail' source.id %}">{{ source.name }}</a></li>
			{% endif %}
		{% endfor %}
		<br>
	</div>
	<div class="w3-third w3-center">
		<h2>Category</h2>
		{% for source in source_category|dictsort:"name" %}
			<li class="w3-sourcelinks w3-center"><a class="w3-sourcelinks w3-hover-red" href="{% url 'source:category' source.id %}">{{ source.name }}</a></li>
		{% endfor %}
	</div>
	<div class="w3-third w3-right">
		<h2 style="text-align:right;">Organization</h2>
		{% for source in source_organization|dictsort:"organization" %}
			<li class="w3-sourcelinks" style="text-align:right;"><a class="w3-sourcelinks w3-hover-red" href="{% url 'source:organization' source.organization %}">{{ source.organization }}</a></li>
		{% endfor %}
	</div>
</div>
{% endblock content %}

source/templates/source/organization.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}
<h1>{{ organization }}</h1>
<div class="w3-barnav w3-container">
	<div class="w3-left w3-margin-left">
		{% for source in source_list|dictsort:"name" %}
			{% if source.is_active is True%}
				<li class="w3-sourcelinks w3-hover-red"><a class="w3-sourcelinks" href="{% url 'source:detail' source.id %}">{{ source.name }} - {{ source.description }}</a></li>
			{% endif %}
		{% endfor %}
		<br>
	</div>
</div>
{% endblock content %}

source/templates/source/quotes.html
{% extends "base.html" %}

{% block title %}Source - Quote of the Day{% endblock title %}

{% block content %}
	{% for key in JSON.items %}
    		<ul>{{ key }}</ul>
	{% endfor %}
{% endblock content %}

source/templates/source/rssfeed.html
{% extends "base.html" %}

{% block title %}Source - RSS Feed{% endblock title %}

{% block content %}
<form class="w3-text-red w3-padding">
<input type="checkbox" name="source_rssfeed" value="True"> Add Source
</form>
<div class="w3-border w3-border-color">
	<div class="w3-center">	
	<h1>Available Web Link / RSS Feed Data</h1>
	</div>
	<div class=" w3-sourcecontent w3-slim">
		<div class="w3-row-padding w3-border-top">
				<div class="w3-quarter">
					<p>Feed Title</p>
				</div>
				<div class="w3-threequarter w3-border-left">
					<p>{{ JSON.feed_title }}</p>
				</div>
		</div>
		<div class="w3-row-padding">
				<div class="w3-quarter">
					<p>Feed Description</p>
				</div>
				<div class="w3-threequarter w3-border-left">
					<p>{{ JSON.feed_description }}</p>
				</div>
		</div>
		<div class="w3-row-padding">
				<div class="w3-quarter">
					<p>Item Title</p>
				</div>
				<div class="w3-threequarter w3-border-left">
					<p>{{ JSON.item_title }}</p>
				</div>
		</div>
		<div class="w3-row-padding">
				<div class="w3-quarter">
					<p>Item Link</p>
				</div>
				<div class="w3-threequarter w3-border-left">
					<p>{{ JSON.item_link }}</p>
				</div>
		</div>
	</div>
</div>
{% endblock content %}
\

source/templates/source/sourcecontent.html
{% extends "base.html" %}

{% block title %}Source - Content{% endblock title %}

{% block content %}
<form class="w3-text-red w3-padding">
<input type="checkbox" name="source_content" value="True"> Add Source
</form>
<div class="w3-border w3-border-color">
	<div class="w3-center w3-border w3-border-color">	
	<h1>Available Data: Web Link (RSS)</h1>
	</div>
	<div class="w3-sourcecontent">
		<div class="w3-center w3-border">
		{% for key, value in JSON.items %}
			<div class="w3-row">
				<div class=" w3-left w3-quarter">
				<p class="" style="text-align:right; font-weight: bold; ">{{ key }}</p>
				</div>
				<div class="w3-right w3-threequarter w3-padding-left w3-padding-right" style="text-align:left;">
				<p>{{ value }}</p>
				</div>
			</div>
			{% for key2, value2 in value.items %}
				<div class="w3-row">
					<div class="w3-quarter w3-left" style="text-align:right; font-weight: bold;">
					<p>{{ key }}.{{ key2 }}</p>
					</div>
					<div class="w3-threequarter w3-right w3-padding-left w3-padding-right" style="text-align:left;">
					<p>{{ value2 }}</p>
					</div>
				</div>
				{% for key3, value3 in value2.items %}
					<div class="w3-row">
						<div class="w3-quarter w3-left" style="text-align:right; font-weight: bold;">
						<p>{{ key3 }}</p>
						</div>
						<div class="w3-threequarter w3-right w3-padding-left w3-padding-right" style="text-align:left;">
						<p>{{ value3 }}</p>
						</div>
					</div>
				{% endfor %}
			{% endfor %}

		{% endfor %}
		</div>
	</div>
</div>
{% endblock content %}